env:
  PYTHON_VERSION: '3.7'
  WORKING_DIRECTORY: './src/'
  STARTUP_COMMAND: ''
  
name: GitHub Actions Demo
on: push
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Check out repository code
        uses: actions/checkout@v4  
      
      - name: Set up Python version
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      
      - name: Create and start virtual environment
        run: |
            python -m venv venv
            source venv/bin/activate

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Log into Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Bicep file
        uses: azure/arm-deploy@v1
        with:
          scope: resourcegroup
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ secrets.AZURE_RG }}
          template: ${{ github.workspace }}/deployment/app-deployment.bicep
          parameters: "appServicePlanName=bannyappplan webAppName=${{ secrets.WEBAPP_NAME }}"
          failOnStdErr: false
      
      - uses: azure/appservice-settings@v1
        with:
          app-name: ${{ secrets.WEBAPP_NAME }}
          mask-inputs: false
          general-settings-json: '{"linuxFxVersion": "PYTHON|${{ env.PYTHON_VERSION }}"}' #'General configuration settings as Key Value pairs'

      - uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.WEBAPP_NAME }}
          package: ${{ env.WORKING_DIRECTORY }}
          startup-command: ${{ env.STARTUP_COMMAND }}