name: GitHub Actions Manual
on: workflow_dispatch
jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3

        - uses: azure/powershell@v2
          with:
            inlineScript:  ./deployment/updateAppPoolsStatusScript.ps1 -authToken 123 -appPoolId 33 -deploymentStatus Deploying
            azPSVersion: "latest"