name: GitHub Actions Manual
on: workflow_dispatch
jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
        - name: Run webhook
          run: |
            curl \
            -H 'X-Status: Awesome' \
            -H 'Content-Type: application/json' \
            -d { "id":"${{github.event.workflow}}","deploymentStatus": "Deployed" } \
            https://www.toptal.com/developers/postbin/1712950287334-0518085097428