name: GitHub Actions Manual
on: workflow_dispatch
jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
        - name: Run webhook
          run: |
            curl \
            -H 'X-Status: Awesome' \
            -H 'Content-Type: application/json' \
            -H 'Authorization: Bearer 12345' \
            https://1833kkkn-7178.uks1.devtunnels.ms/api/update-app-pool-deployment \
            -d '{"id":"33","deploymentStatus":"Deployed"}'
#            -d '{"id": 0,"storageAccountName": "${{github.action}}","searchServiceName": "${{github.action}}","openAIServiceName": "${{github.action}}","appServicePlanName": "${{github.action}}","appPlanSku": "${{github.action}}"}'